---

kind: pipeline
type: docker
name: default

#
# Steps
#

steps:
- name: nosetests
  image: docker:19.03-dind
  when:
    event:
    - push
  volumes:
  - name: docker_socket
    path: /var/run
  environment:
    DOCKER_HOST: unix:///var/run/docker.sock
  commands:
  - export image=opertusmundi/geoprofile:${DRONE_COMMIT}-testing
  - (t=10; while ! docker info -f '{{.ID}}' 2>/dev/null; do t=$((t - 1)); test $${t} -ne 0; sleep 1; done)
  - docker build . -f testing.dockerfile --build-arg VERSION=${DRONE_COMMIT} -t $${image}
  - mkdir output data temp && chown -v 1000:1000 output data temp
  - export env_file=nosetests-${CI_BUILD_NUMBER}.env
  - >-
    (env -i
    TEMPDIR=/work/temp
    OUTPUT_DIR=/work/output
    INSTANCE_PATH=/work/data
    DATABASE=/work/data/geoprofile-testing.sqlite
    ) | tee $${env_file}
  - docker run --rm -u 1000:1000 -v $PWD:/work -w /work --env-file $${env_file} $${image}

- name: prepare-tags
  image: busybox:1.32
  when:
    event:
    - tag
  commands:
  - tags_file=$(mktemp) 
  - echo ${DRONE_TAG} | grep -e '^[0-9]\+[.][0-9]\+[.][0-9]\+\([_-][a-z0-9][-.a-z0-9]*\)\?$' | tee -a $${tags_file}
  - echo ${DRONE_TAG} | grep -o -e '^[0-9]\+[.][0-9]\+[.][0-9]\+' | tee -a $${tags_file}
  - cat $${tags_file} | xargs echo | tr '[:blank:]' ',' | tr -d '\n' | tee .tags && echo

- name: publish-image-1
  image: plugins/docker
  when:
    event:
    - tag
  settings:
    debug: true
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: opertusmundi/profile
    mirror: http://registry-mirror:5000
    build_args:
    - VERSION=${DRONE_TAG}

- name: publish-image-2
  image: plugins/docker
  when:
    event:
    - tag
  settings:
    debug: true
    username: 
      from_secret: registry_username
    password:
      from_secret: registry_password
    repo: registry-dev-1-opertusmundi:30474/opertusmundi/profile
    mirror: http://registry-mirror:5000
    registry: registry-dev-1-opertusmundi:30474
    build_args:
    - VERSION=${DRONE_TAG}

#
# Services
#

services:
- name: docker
  image: docker:19.03-dind
  privileged: true
  command:
  - --registry-mirror=http://registry-mirror:5000
  volumes:
  - name: docker_socket
    path: /var/run

volumes:
- name: docker_socket
  temp: {}

